saas_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: .local/saas_analytics.duckdb
      schema: main
    prod:
      type: duckdb
      path: .local/saas_analytics.duckdb
      schema: prod
