saas_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /usr/app/dbt/saas_analytics/saas_analytics.duckdb
      schema: main
    prod:
      type: duckdb
      path: /usr/app/dbt/saas_analytics/saas_analytics.duckdb
      schema: prod
