version: 2

models:
  - name: stg_accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: referral_source
        tests:
          - accepted_values:
              arguments:
                values: ['organic', 'ads', 'event', 'partner', 'other']
      - name: plan_tier
        tests:
          - accepted_values:
              arguments:
                values: ['Basic', 'Pro', 'Enterprise']

  - name: stg_subscriptions
    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id
      - name: plan_tier
        tests:
          - accepted_values:
              arguments:
                values: ['Basic', 'Pro', 'Enterprise']
      - name: billing_frequency
        tests:
          - accepted_values:
              arguments:
                values: ['monthly', 'annual']

  - name: stg_feature_usage
    columns:
      - name: usage_id
        tests:
          - not_null
          # - unique
      - name: subscription_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_subscriptions')
                field: subscription_id

  - name: stg_support_tickets
    columns:
      - name: ticket_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id
      - name: priority
        tests:
          - accepted_values:
              arguments:
                values: ['low', 'medium', 'high', 'urgent']

  - name: stg_churn_events
    columns:
      - name: churn_event_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id
